#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-pycparser
Version  : 2.19
Release  : 54
URL      : https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz
Source0  : https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz
Summary  : C parser in Python
Group    : Development/Tools
License  : BSD-3-Clause
Requires: deprecated-pycparser-license = %{version}-%{release}
Requires: deprecated-pycparser-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : python-dev

%description
===============
pycparser v2.19
===============
:Author: `Eli Bendersky <https://eli.thegreenplace.net/>`_

%package legacypython
Summary: legacypython components for the deprecated-pycparser package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-pycparser package.


%package license
Summary: license components for the deprecated-pycparser package.
Group: Default

%description license
license components for the deprecated-pycparser package.


%package python
Summary: python components for the deprecated-pycparser package.
Group: Default

%description python
python components for the deprecated-pycparser package.


%prep
%setup -q -n pycparser-2.19

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554325573
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python tests/all_tests.py
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-pycparser
cp LICENSE %{buildroot}/usr/share/package-licenses/deprecated-pycparser/LICENSE
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-pycparser/LICENSE

%files python
%defattr(-,root,root,-)
